### ISSUE TITLE
"ggit last -f build.json" failing in 1.9.0

### ISSUE THREAD

**Issue by theGrue** [bahmutov/ggit#32]
On Windows (abbreviated some paths):
> ggit last -f build.json

C:\...\api\node_modules\ggit\src\git-folder.js:9
        throw new Error('Cannot find file ' + gitDirLocation);
        ^

Error: Cannot find file ./.git
    at getGitFolder (C:\...\api\node_modules\ggit\src\git-folder.js:9:15)
    at Object.<anonymous> (C:\...\api\node_modules\ggit\src\commit-message.js:4:39)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\...\api\node_modules\ggit\index.js:20:17)
    at Module._compile (module.js:409:26)

On Linux:
> ggit last -f build.json

/data/api/node_modules/ggit/src/git-folder.js:9
        throw new Error('Cannot find file ' + gitDirLocation);
        ^

Error: Cannot find file ./.git
    at getGitFolder (/data/api/node_modules/ggit/src/git-folder.js:9:15)
    at Object.<anonymous> (/data/api/node_modules/ggit/src/commit-message.js:4:39)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/data/api/node_modules/ggit/index.js:20:17)
    at Module._compile (module.js:409:26)

**Comment by tamascsaba** [comment]
+1
